---
- name: Secured Apache with a .NET application
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Enable mod_proxy module
      shell: a2enmod proxy proxy_http

    - name: Install ModSecurity
      apt:
        name: libapache2-mod-security2
        state: present

    - name: Install modsecurity-crs
      apt:
        name: modsecurity-crs
        state: present

    - name: Enable ModSecurity
      shell: a2enmod security2

    - name: Copy ModSecurity configuration
      copy:
        src: /etc/modsecurity/modsecurity.conf-recommended
        dest: /etc/modsecurity/modsecurity.conf
        remote_src: true

    - name: Change ModSecurity to enforced mode
      replace:
        path: /etc/modsecurity/modsecurity.conf
        regexp: 'SecRuleEngine DetectionOnly'
        replace: 'SecRuleEngine On'

    - name: Restart Apache to apply changes
      systemd:
        name: apache2
        state: restarted

    - name: Install packages required by Microsoft package feed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gpg
        state: present

    - name: Register the Microsoft package feed
      shell: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        mv microsoft.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/11/prod bullseye main" > /etc/apt/sources.list.d/microsoft-prod.list
        apt-get update

    - name: Install .NET
      apt:
        name:
          - dotnet-sdk-6.0
        state: present

    - name: Clone the .NET app source code
      git:
        repo: 'https://github.com/hablutzel1/upc_is277_protected_apache_with_dotnet.git'
        dest: /var/www/sampleapp
        depth: 1

    - name: Publish the .NET application
      shell: |
        cd /var/www/sampleapp/APP
        dotnet publish -c Release

    - name: Create .NET service
      copy:
        dest: /etc/systemd/system/sampleapp.service
        content: |
          [Unit]
          Description=Sample .NET Web App running on Debian 11

          [Service]
          WorkingDirectory=/var/www/sampleapp/APP/APP_ArqComputadorasV2/bin/Release/net6.0/publish/
          ExecStart=/usr/bin/dotnet /var/www/sampleapp/APP/APP_ArqComputadorasV2/bin/Release/net6.0/publish/APP_ArqComputadorasV2.dll
          Restart=always
          # Restart service after 10 seconds if the dotnet service crashes:
          RestartSec=10
          KillSignal=SIGINT
          SyslogIdentifier=dotnet-sampleapp
          User=www-data
          Environment=ASPNETCORE_ENVIRONMENT=Production 

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start .NET service
      systemd:
        name: sampleapp
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Configure Apache to proxy requests
      copy:
        dest: /etc/apache2/sites-available/sampleapp.conf
        content: |
          <VirtualHost *:80>
              ProxyPreserveHost On
              ProxyPass / http://localhost:5000/
              ProxyPassReverse / http://localhost:5000/
              ErrorLog ${APACHE_LOG_DIR}/sampleapp-error.log
              CustomLog ${APACHE_LOG_DIR}/sampleapp-access.log common
          </VirtualHost>

    - name: Disable default site
      shell: a2dissite 000-default

    - name: Enable site
      shell: a2ensite sampleapp

    - name: Restart Apache to apply changes
      systemd:
        name: apache2
        state: restarted
